#include "cpu.h"

void op_nop(cpu_t* cpu);
void op_wdm(cpu_t* cpu);
void op_xba(cpu_t* cpu);
void op_move_b(cpu_t* cpu, int adjust);
void op_move_w(cpu_t* cpu, int adjust);
void op_interrupt_e(cpu_t* cpu, int vectorE, int vectorN);
void op_interrupt_n(cpu_t* cpu, int vectorE, int vectorN);
void op_stp(cpu_t* cpu);
void op_wai(cpu_t* cpu);
void op_xce(cpu_t* cpu);
void op_flag(cpu_t* cpu);
void op_pflag_e(cpu_t* cpu, int mode);
void op_pflag_n(cpu_t* cpu, int mode);
void op_transfer_b(cpu_t* cpu, int from, int to);
void op_transfer_w(cpu_t* cpu, int from, int to);
void op_tcs_e(cpu_t* cpu);
void op_tcs_n(cpu_t* cpu);
void op_tsx_b(cpu_t* cpu);
void op_tsx_w(cpu_t* cpu);
void op_txs_e(cpu_t* cpu);
void op_txs_n(cpu_t* cpu);
void op_push_b(cpu_t* cpu, int n);
void op_push_w(cpu_t* cpu, int n);
void op_phd_e(cpu_t* cpu);
void op_phd_n(cpu_t* cpu);
void op_phb(cpu_t* cpu);
void op_phk(cpu_t* cpu);
void op_php(cpu_t* cpu);
void op_pull_b(cpu_t* cpu, int n);
void op_pull_w(cpu_t* cpu, int n);
void op_pld_e(cpu_t* cpu);
void op_pld_n(cpu_t* cpu);
void op_plb(cpu_t* cpu);
void op_plp_e(cpu_t* cpu);
void op_plp_n(cpu_t* cpu);
void op_pea_e(cpu_t* cpu);
void op_pea_n(cpu_t* cpu);
void op_pei_e(cpu_t* cpu);
void op_pei_n(cpu_t* cpu);
void op_per_e(cpu_t* cpu);
void op_per_n(cpu_t* cpu);
