#ifndef MOCKUP_MISC_HPP
#define MOCKUP_MISC_HPP

char* sprite_names[256] = {
    "Green Koopa, no shell",
    "Red Koopa, no shell",
    "Blue Koopa, no shell",
    "Yellow Koopa, no shell",
    "Green Koopa",
    "Red Koopa",
    "Blue Koopa",
    "Yellow Koopa",
    "Green Koopa, flying left",
    "Green bouncing Koopa",
    "Red vertical flying Koopa",
    "Red horizontal flying Koopa",
    "Yellow Koopa with wings",
    "Bob-omb",
    "Keyhole",
    "Goomba",
    "Bouncing Goomba with wings",
    "Buzzy Beetle",
    "Unused",
    "Spiny",
    "Spiny falling",
    "Fish, horizontal",
    "Fish, vertical",
    "Fish, created from generator",
    "Surface jumping fish",
    "Display text from level Message Box #1",
    "Classic Piranha Plant",
    "Bouncing football in place",
    "Bullet Bill",
    "Hopping flame",
    "Lakitu",
    "Magikoopa",
    "Magikoopa's magic",
    "Moving coin",
    "Green vertical net Koopa",
    "Red vertical net Koopa",
    "Green horizontal net Koopa",
    "Red horizontal net Koopa",
    "Thwomp",
    "Thwimp",
    "Big Boo",
    "Koopa Kid",
    "Upside down Piranha Plant",
    "Sumo Brother's fire lightning",
    "Yoshi egg",
    "Baby green Yoshi",
    "Spike Top",
    "Portable spring board",
    "Dry Bones, throws bones",
    "Bony Beetle",
    "Dry Bones, stay on ledge",
    "Fireball",
    "Boss fireball",
    "Green Yoshi",
    "Unused",
    "Boo",
    "Eerie",
    "Eerie, wave motion",
    "Urchin, fixed",
    "Urchin, wall detect",
    "Urchin, wall follow",
    "Rip Van Fish",
    "POW",
    "Para-Goomba",
    "Para-Bomb",
    "Dolphin, horizontal",
    "Dolphin2, horizontal",
    "Dolphin, vertical",
    "Torpedo Ted",
    "Directional coins",
    "Diggin' Chuck",
    "Swimming/Jumping fish",
    "Diggin' Chuck's rock",
    "Growing/shrinking pipe end",
    "Goal Point Question Sphere",
    "Pipe dwelling Lakitu",
    "Exploding Block",
    "Ground dwelling Monty Mole",
    "Ledge dwelling Monty Mole",
    "Jumping Piranha Plant",
    "Jumping Piranha Plant, spit fire",
    "Ninji",
    "Moving ledge hole in ghost house",
    "Throw block sprite",
    "Climbing net door",
    "Checkerboard platform, horizontal",
    "Flying rock platform, horizontal",
    "Checkerboard platform, vertical",
    "Flying rock platform, vertical",
    "Turn block bridge, horizontal and vertical",
    "Turn block bridge, horizontal",
    "Brown platform floating in water",
    "Checkerboard platform that falls",
    "Orange platform floating in water",
    "Orange platform, goes on forever",
    "Brown platform on a chain",
    "Flat green switch palace switch",
    "Floating skulls",
    "Brown platform, line-guided",
    "Checker/brown platform, line-guided",
    "Rope mechanism, line-guided",
    "Chainsaw, line-guided",
    "Upside down chainsaw, line-guided",
    "Grinder, line-guided",
    "Fuzz ball, line-guided",
    "Unused",
    "Coin game cloud",
    "Spring board, left wall",
    "Spring board, right wall",
    "Invisible solid block",
    "Dino Rhino",
    "Dino Torch",
    "Pokey",
    "Super Koopa, red cape",
    "Super Koopa, yellow cape",
    "Super Koopa, feather",
    "Mushroom",
    "Flower",
    "Star",
    "Feather",
    "1-Up",
    "Growing Vine",
    "Firework",
    "Goal Point",
    "Princess Peach",
    "Balloon",
    "Flying Red coin",
    "Flying yellow 1-Up",
    "Key",
    "Changing item from translucent block",
    "Bonus game sprite",
    "Left flying question block",
    "Flying question block",
    "Unused (Pretty sure)",
    "Wiggler",
    "Lakitu's cloud",
    "Unused (Winged cage sprite)",
    "Layer 3 smash",
    "Bird from Yoshi's house",
    "Puff of smoke from Yoshi's house",
    "Fireplace smoke/exit from side screen",
    "Ghost house exit sign and door",
    "Invisible \"Warp Hole\" blocks",
    "Scale platforms",
    "Large green gas bubble",
    "Chargin' Chuck",
    "Splittin' Chuck",
    "Bouncin' Chuck",
    "Whistlin' Chuck",
    "Clapin' Chuck",
    "Unused (Chargin' Chuck clone)",
    "Puntin' Chuck",
    "Pitchin' Chuck",
    "Volcano Lotus",
    "Sumo Brother",
    "Hammer Brother",
    "Flying blocks for Hammer Brother",
    "Bubble with sprite",
    "Ball and Chain",
    "Banzai Bill",
    "Activates Bowser scene",
    "Bowser's bowling ball",
    "MechaKoopa",
    "Grey platform on chain",
    "Floating Spike ball",
    "Fuzzball/Sparky, ground-guided",
    "HotHead, ground-guided",
    "Iggy's ball",
    "Blargg",
    "Reznor",
    "Fishbone",
    "Rex",
    "Wooden Spike, moving down and up",
    "Wooden Spike, moving up/down first",
    "Fishin' Boo",
    "Boo Block",
    "Reflecting stream of Boo Buddies",
    "Creating/Eating block",
    "Falling Spike",
    "Bowser statue fireball",
    "Grinder, non-line-guided",
    "Sinking fireball used in boss battles",
    "Reflecting fireball",
    "Carrot Top lift, upper right",
    "Carrot Top lift, upper left",
    "Info Box",
    "Timed lift",
    "Grey moving castle block",
    "Bowser statue",
    "Sliding Koopa without a shell",
    "Swooper bat",
    "Mega Mole",
    "Grey platform on lava",
    "Flying grey turnblocks",
    "Blurp fish",
    "Porcu-Puffer fish",
    "Grey platform that falls",
    "Big Boo Boss",
    "Dark room with spot light",
    "Invisible mushroom",
    "Light switch block for dark room",
    "Bullet Bill shooter",
    "Torpedo Launcher",
    "Eerie, generator",
    "Para-Goomba, generator",
    "Para-Bomb, generator",
    "Para-Bomb and Para-Goomba, generator",
    "Dolphin, left, generator",
    "Dolphin, right, generator",
    "Jumping fish, generator",
    "Turn off generator 2 (sprite E5)",
    "Super Koopa, generator",
    "Bubble with Goomba and Bob-omb, generator",
    "Bullet Bill, generator",
    "Bullet Bill surrounded, generator",
    "Bullet Bill diagonal, generator",
    "Bowser statue fire breath, generator",
    "Turn off standard generators",
    "Green Koopa shell",
    "Red Koopa shell",
    "Blue Koopa shell",
    "Yellow Koopa shell",
    "Group of 5 eeries, wave motion",
    "Green bouncing Koopa shell",
    "3 platforms on chains",
    "Ghost ceiling",
    "Boo Buddies, counter clockwise",
    "Boo Buddies, clockwise",
    "Swooper bat ceiling",
    "Reappearing ghost, generator 2",
    "Candle flame background",
    "Auto-Scroll, Unused?",
    "Auto-Scroll",
    "Layer 2 Smash",
    "Layer 2 Scroll",
    "Unused",
    "Unused",
    "Layer 2 Falls",
    "Unused",
    "Layer 2 Scroll",
    "Unused",
    "Unused",
    "Layer 2 On/Off Switch controlled",
    "Auto-Scroll level",
    "Fast BG scroll",
    "Layer 2 sink/rise",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error",
    "Unused, fatal error"
};

#endif //MOCKUP_MISC_HPP
